[package]
name = "tauri-plugin-positioner"
version = "0.0.0"
authors = [ "Jonas Kruckenberg" ]
description = "Helps positioning your tauri windows."
edition = "2021"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]

[dependencies]
tauri = { version = "1.0.0-beta.8", features = [ "api-all" ] }
serde = "1.0"
serde_repr = "0.1"
